export const InputArr = [
    {
        id:0,
        title:`React Validation - Normal`,
        description:'Provide valuable, actionable feedback to your users with HTML5 form validation–available in all our supported browsers.',
        classNames:'form_validation_bottom_wrapper',
        checkbox:true,
        btnName:'Submit form',
        btnCanel:'canel',
        btnCanelType:false,
        data:[
            {
                id:0,
                type:'text',
                placehold:'First name',
                labels:'First name',
                classWrapper:'',
                blockClass:'',
                errorText:'Enter First name',
                inputClass:'form_validation_input_block',
                btnName:'Submit form',
                labelsid:'reactFirstName',
            },
            {
                id:1,
                type:'text',
                placehold:'Last name',
                inputClass:'form_validation_input_block',
                labels:'Last name',
                classWrapper:'',
                blockClass:'',
                errorText:'Enter Last name',
                btnName:'Submit form',
                btnCanel:'canel',
                btnCanelType:true,
                labelsid:'reactLastName',
            },
            {
                id:2,
                type:'text',
                placehold:'City',
                labels:'City',
                classWrapper:'',
                blockClass:'',
                inputClass:'form_validation_input_block',
                errorText:'Please provide a valid city.\n',
                btnName:'Submit form',
                labelsid:'reactCity',
            },
            {
                id:3,
                type:'text',
                placehold:'State',
                labels:'State',
                classWrapper:'',
                blockClass:'',
                errorText:'Please provide a valid State.\n',
                btnName:'Submit form',
                inputClass:'form_validation_input_block',
                labelsid:'reactState',
            },
        ]


    },
    {
        id:1,
        title:`Bootstrap Validation (Tooltips)`,
        description:'If your form layout allows it, you can swap the .-feedback classes for .-tooltip classes to display validation feedback in a styled tooltip.\n',
        classNames:'form_validation_bottom_wrapper',
        checkbox:false,
        btnName:'Submit form',
        btnCanel:'canel',
        btnCanelType:false,
        data:[
            {
                id:0,
                type:'text',
                placehold:'First name',
                labels:'First name',
                classWrapper:'',
                labelsid:'bootstrapFirstName',
                blockClass:'',
                errorText:'Please Enter Valid First Name',
                inputClass:'form_validation_input_block',
            },
            {
                id:1,
                type:'text',
                placehold:'Last name',
                labelsid:'bootstrapLastName',
                labels:'Last name',
                classWrapper:'',
                blockClass:'',
                errorText:'Please Enter Valid Last Name',
                btnName:'Submit form',
                inputClass:'form_validation_input_block',
            },
            {
                id:2,
                type:'text',
                placehold:'Username',
                labels:'Username',
                classWrapper:'',
                blockClass:'',
                errorText:'Please choose a unique and valid username.',
                btnName:'Submit form',
                btnCanel:'canel',
                btnCanelType:true,
                labelsid:'bootstrapUserName',
                inputClass:'form_validation_input_block',
            },
            {
                id:3,
                type:'text',
                placehold:'City',
                labels:'City',
                classWrapper:'',
                blockClass:'',
                errorText:'Please choose a unique and valid username.Please provide a valid city.',
                btnName:'Submit form',
                inputClass:'form_validation_input_block',
                labelsid:'bootstrapCity',
            },
        ]


    },
    {
        id:2,
        title:`Validation type`,
        description:'Parsley is a availity reactstrap validation. It helps you provide your users with feedback on their form submission before sending it to your server.',
        classNames:'form_validation_bottom_wrapper-block',
        checkbox:false,
        btnName:'Submit form',
        btnCanel:'canel',
        btnCanelType:true,
        data:[
            {
                id:0,
                type:'text',
                placehold:'Type something',
                labels:'Required',
                classWrapper:'',
                inputClass:'form_validation_input_block-block',
                blockClass:'',
                errorText:'Enter name',
                labelsid:'Required',
            },
            {
                id:1,
                type:'password',
                placehold:'Password',
                labels:'Equal To',
                classWrapper:'',
                blockClass:'',
                errorText:'Enter password',
                inputClass:'form_validation_input_block-block',
                labelsid:'password',
            },
            {
                id:2,
                type:'password',
                placehold:'Re-type-Password',
                classWrapper:'',
                blockClass:'',
                errorText:'Enter First name',
                inputClass:'form_validation_input_block-block',
                labelsid:'RePassword',
            },
            {
                id:3,
                type:'mailto',
                placehold:'Enter Valid Email',
                labels:'E-Mail',
                classWrapper:'',
                blockClass:'',
                errorText:'Invalid Email',
                labelsid:'Email',
                inputClass:'form_validation_input_block-block',
            },
            {
                id:4,
                type:'text',
                placehold:'Enter Only Digits',
                labels:'Digits',
                classWrapper:'',
                blockClass:'',
                errorText:'Enter Only Digits',
                inputClass:'form_validation_input_block-block',
                labelsid:'Digits',
            },
            {
                id:5,
                type:'number',
                placehold:'Enter Only number',
                labels:'Number',
                classWrapper:'',
                blockClass:'',
                errorText:'Enter Only number',
                inputClass:'form_validation_input_block-block',
                labelsid:'number',
            },
            {
                id:6,
                type:'text',
                placehold:'Enter Only alphanumeric value',
                labels:'Alphanumeric',
                classWrapper:'',
                blockClass:'',
                errorText:'Enter Only Alphanumeric',
                inputClass:'form_validation_input_block-block',
                labelsid:'alphanumeric',
            },
        ]


    },
    {
        id:3,
        title:`Range validation`,
        description:'Parsley is a availity reactstrap validation. It helps you provide your users with feedback on their form submission before sending it to your server.',
        classNames:'form_validation_bottom_wrapper-block',
        checkbox:false,
        btnName:'Submit form',
        btnCanel:'canel',
        btnCanelType:true,
        data:[
            {
                id:0,
                type:'text',
                placehold:'Min 6 chars',
                labels:'Min Length',
                classWrapper:'',
                blockClass:'',
                errorText:'Min 6 chars',
                inputClass:'form_validation_input_block-block',
                labelsid:'min6',
            },
            {
                id:1,
                type:'text',
                placehold:'Max 6 chars',
                labels:'Max Length',
                classWrapper:'',
                blockClass:'',
                errorText:'Enter First name',
                inputClass:'form_validation_input_block-block',
                labelsid:'max6',
            },
            {
                id:2,
                type:'text',
                placehold:'Text between 5 - 10 chars length',
                labels:'Range Length',
                classWrapper:'',
                blockClass:'',
                errorText:'range between 5 to 10',
                inputClass:'form_validation_input_block-block',
                labelsid:'textBetween',
            },
            {
                id:3,
                type:'text',
                placehold:'Min 6 chars',
                labels:'Min Value',
                classWrapper:'',
                blockClass:'',
                errorText:'Min value 6 ',
                inputClass:'form_validation_input_block-block',
                labelsid:'minValue',
            },
            {
                id:4,
                type:'text',
                placehold:'max 5 Chars',
                labels:'Max Value',
                classWrapper:'',
                blockClass:'',
                errorText:'max 6 chars',
                inputClass:'form_validation_input_block-block',
                labelsid:'maxValue',
            },
            {
                id:5,
                type:'text',
                placehold:'This value should be between 6 and 100.',
                labels:'Range Value',
                classWrapper:'',
                blockClass:'',
                errorText:'range between 5 to 10',
                inputClass:'form_validation_input_block-block',
                labelsid:'rangValue',
            },
            {
                id:6,
                type:'text',
                placehold:'Hex. Color ',
                labels:'Regular Exp',
                classWrapper:'',
                blockClass:'',
                errorText:'Hex Value',
                inputClass:'form_validation_input_block-block',
                labelsid:'RegularExp',
            },
        ]


    },


]