export const CONSTANTS = {
  CLEAR_ON_SUBMIT: "CLEAR_ON_SUBMIT",
  REFRESH_ACCESS_TOKEN: "REFRESH_ACCESS_TOKEN",
  SET_AUTH_CREDENTIALS: "SET_AUTH_CREDENTIALS",
  SET_AUTH_TOKENS: "SET_AUTH_TOKENS",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  CLEAR_ON_SIGNOUT: "CLEAR_ON_SIGNOUT",
};
